spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1010a
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#html
thymeleaf:
    cache: false
#rebushu
devtools:
    restart:
      enabled: true
mvc:
    static-path-pattern: /static/**
    view:
      prefix: /jsps/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.zy.demo.pojo
#tuofeng
  configuration:
    map-underscore-to-camel-case: true
#log4j
logging:
  level:
    com.zy.demo.mapper: debug
#rebushu
server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 9090